export const projectsList = [
  {
    id: 7,
    pinned: true,
    img: {
      src: "images/projects/react-personal-website.png",
      alt: "React Personal Website Home Page",
    },
    title: "React Personal Website",
    date: "08/05/2022",
    languages: "JavaScript, React, Styled Components",
    github: "https://github.com/alx-zhu/react-personal-website",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 6,
    pinned: true,
    img: {
      src: "images/projects/react-todo-list.png",
      alt: "React Todo List",
    },
    title: "React Todo List",
    date: "06/14/2022",
    languages: "JavaScript, CSS, React",
    github: "https://github.com/alx-zhu/todo-list",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 5,
    img: {
      src: "images/projects/js-todo-list.png",
      alt: "JS Todo List",
    },
    title: "JS Todo List",
    date: "05/24/2022",
    languages: "HTML, JavaScript, CSS, React",
    github: "https://github.com/alx-zhu/todo-list",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 4,
    img: {
      src: "images/projects/html-css-website.png",
      alt: "HTML Personal Website Home Page",
    },
    title: "HTML/CSS Personal Website",
    date: "05/09/2022",
    languages: "HTML, CSS",
    github: "https://github.com/alx-zhu/html-personal-website",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 3,
    img: {
      src: "images/projects/cave-generator.png",
      alt: "Cave Generator",
    },
    title: "Cell Automata Cave Generator",
    date: "05/06/2022",
    languages: "Python, CMU Graphics",
    github: "https://github.com/alx-zhu/CaveGenerator",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 2,
    pinned: true,
    img: {
      src: "images/projects/labyrinth-thumbnail.png",
      alt: "Andy's Labyrinth Thumbnail",
    },
    title: "Andy's Labyrinth",
    date: "12/02/2021",
    languages: "Python, CMU Graphics",
    github: "https://github.com/alx-zhu/AndysLabyrinth",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
  {
    id: 1,
    pinned: true,
    img: {
      src: "images/projects/pgpatch-thumbnail.png",
      alt: "The Pacific Garbage Patch",
    },
    title: "The Pacific Garbage Patch",
    date: "06/22/2021",
    languages: "Unity Game Engine, C#",
    github: "https://github.com/alx-zhu/ThePacificGarbagePatch",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim. Vitae sapien pellentesque habitant morbi tristique senectus. Ultrices gravida dictum fusce ut placerat orci. Neque gravida in fermentum et sollicitudin ac orci. Proin libero nunc consequat interdum varius. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Dignissim diam quis enim lobortis scelerisque fermentum. At augue eget arcu dictum varius duis at. Ut placerat orci nulla pellentesque dignissim enim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet risus nullam eget felis eget nunc lobortis mattis.",
    clickable: true,
  },
];
